Adição do Footer ao projeto.
DCFS5S/dripstore pull request #10
Opened 2023-07-30 23:42 UTC by Alessa1947

Foi adicionado um rodapé dividido em 4 partes para a resolução dos códigos dentro do body e espaçamento fixo, como foi solicitado!
Pensando em facilitar o entendimento dos desenvolvedores, os códigos estão claros e objetivos.

2023-07-31 18:30 UTC, ronnyjohnti approved these changes
Bom trabalho!

2023-08-03 22:12 UTC, carlosdigital16 requested changes
Bom trabalho, não verifiquei pixel por pixel mas aparentemente está idêntico ao design. 🎉 

Por favor, confira meus comentários.

2023-08-03 22:12 UTC, carlosdigital16 commented on index.html
> +      <img src="assets/img/social-icons.svg" alt="">
Acredito que as logo deveriam ser elementos distintos.
Favor corrigir! 👀

2023-08-03 22:12 UTC, carlosdigital16 commented on assets/css/main-footer.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700&display=swap');
Vamos precisar dessa em todo o site, precisamos alinhar com o time onde esse código deve ficar.

2023-08-03 22:12 UTC, carlosdigital16 commented on assets/css/main-footer.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700&display=swap');
Verificar se todos os pesos da fonte estão sendo utilizados no design

2023-08-03 22:12 UTC, carlosdigital16 commented on assets/css/main-footer.css
> +.main-footer #footer1{
Acredito que dá pra melhorar o nome desse ID, footer1 não me parece muito explicativo.

2023-08-03 22:12 UTC, carlosdigital16 commented on assets/css/main-footer.css
> +.main-footer #footer1{
```suggestion
.main-footer #footer1 {
```

2023-08-03 22:12 UTC, carlosdigital16 commented on assets/css/main-footer.css
> +
Favor, remover a linha em branco

2023-08-03 22:12 UTC, carlosdigital16 commented on index.html
> +      <h2> <img src="assets/img/logowhite.svg" alt=""> Digital Store</h2>
Favor, dar preferência a no máximo uma tag por linha

2023-08-03 22:12 UTC, carlosdigital16 commented on index.html
> +      <h2> <img src="assets/img/logowhite.svg" alt=""> Digital Store</h2>
```suggestion
      <h2>
        <img src="assets/img/logowhite.svg" alt="">
        Digital Store
      </h2> 
```

2023-08-08 22:18 UTC, Karpegianny commented on assets/css/main-footer.css
> +
A linha em branco foi removida!

2023-08-08 22:30 UTC, Wiulisam commented on index.html
> +      <h2> <img src="assets/img/logowhite.svg" alt=""> Digital Store</h2>
Tags corrigidas 👍

2023-08-08 22:41 UTC, Karpegianny commented on assets/css/main-footer.css
> +.main-footer #footer1{
Classe main footer renomeada com sucesso!

2023-08-08 23:31 UTC, carlosdigital16 requested changes

2023-08-08 23:31 UTC, carlosdigital16 commented on .vscode/settings.json
> +}
Remover arquivo conflitado

2023-08-08 23:31 UTC, carlosdigital16 commented on index.html
> +          <img src="/assets/img/logo-facebook.png" alt="">
Remove a `/` do inicio do path de todas as imagens

2023-08-08 23:31 UTC, carlosdigital16 commented on index.html
> +    <div id="footer-logo">
`footer-logo` não parece um nome compatível com o elemento.
Sugiro também não usar ids, e usar somente classes.

2023-08-08 23:31 UTC, carlosdigital16 commented on assets/css/main-footer.css
> +  width: 124.12px;
Pixel quebrado não funciona.

2023-12-07 21:37 UTC, carlosdigital16 commented
O PR ficou destualizado

2023-12-07 21:37 UTC, closed without merging