4 secao de produtos em alta 5
DCFS5S/dripstore pull request #13
Opened 2023-08-03 22:16 UTC by PauloF7T

2023-08-03 23:18 UTC, carlosdigital16 requested changes
Ficou excelente! Favor, corrigir os comentários!

2023-08-03 23:18 UTC, carlosdigital16 commented on assets/css/featured-products.css
> +    justify-content: center;
Indentação não está correta.

2023-08-03 23:18 UTC, carlosdigital16 commented on assets/css/featured-products.css
> +  /* height: 321px; */
Favor, remover comentário

2023-08-03 23:18 UTC, carlosdigital16 commented on assets/css/featured-products.css
> +    align-items: center;
Identação 👀

2023-08-03 23:18 UTC, carlosdigital16 commented on assets/css/featured-products.css
> +}
Favor, adicionar uma linha em branco aqui.

2023-08-03 23:18 UTC, carlosdigital16 commented on assets/css/featured-products.css
> +
Remover

2023-08-03 23:18 UTC, carlosdigital16 commented on index.html
> +</body>
Body está duplicado

2023-08-08 22:13 UTC, Jander80 commented on assets/css/featured-products.css
> +    justify-content: center;
obrigado pelo feedback , identação corrigida !

2023-08-08 22:13 UTC, Jander80 commented on assets/css/featured-products.css
> +  /* height: 321px; */
Comentário removido !

2023-08-08 22:15 UTC, Jander80 commented on assets/css/featured-products.css
> +    align-items: center;
Identação corrigida !

2023-08-08 22:15 UTC, Jander80 commented on assets/css/featured-products.css
> +}
Conforme solicitação, linha em branco removida !

2023-08-08 22:16 UTC, Jander80 commented on index.html
> +</body>
Conforme a solicitação , o body duplicado foi excluído.

2023-08-08 22:32 UTC, carlosdigital16 commented
No geral está muito bom, porém ainda tem trabalho a ser feito com relação ao mobile.
Você poderia criar um cartão pra isso no board?

2023-08-08 22:33 UTC, carlosdigital16 approved these changes

2023-08-08 22:34 UTC, Nycaio123 approved these changes

2023-08-08 22:34 UTC, HannielBarros approved these changes

2023-08-08 22:41 UTC, nikelyfedechen approved these changes
Muito bom! Parabéns, pessoal =)

2023-08-08 22:42 UTC, merged