2 criar sessão de destaque 5
DCFS5S/dripstore pull request #14
Opened 2023-08-03 22:23 UTC by fmatheusteixeira

Criação da sessão destaques de acordo com as instruções do card e os pixels do projeto figma, também foi criado as versões com responsividade.

2023-08-08 21:57 UTC, ronnyjohnti commented
Corrigir aspecto/proporções dos elementos `.box`, pois está muito espremido ou esticado em larguras de tela próximas do *breakpoint* de `790px`.
![image](https://github.com/DCFS5S/dripstore/assets/42920699/3028a106-1441-46b1-8f6e-39ee512f1162)
![image](https://github.com/DCFS5S/dripstore/assets/42920699/20da849f-af2e-4c28-a1e7-e9fcf8a10f06)

2023-08-08 21:58 UTC, ronnyjohnti commented on assets/css/featured-collections.css
> +.box {
Recomento alterar o nome da classe `.box`, pois está muito genérico

2023-08-08 22:01 UTC, ronnyjohnti commented on assets/css/featured-collections.css
> +
Algumas das propriedades utilizadas nas classes `.featured-collections_*` poderiam ser colocadas na classe `.box`, como `width`, `heigh` e `background`.

2023-08-08 23:24 UTC, carlosdigital16 requested changes
Favor, verificar mudanças sugeridas!

2023-08-08 23:24 UTC, carlosdigital16 commented on .vscode/settings.json
> +}
Favor, remover arquivo!

2023-08-08 23:24 UTC, carlosdigital16 commented on assets/css/featured-collections.css
> +#destaque {
Utilizar seletores de classe em inglês para manter o padrão do projeto.

2023-08-08 23:24 UTC, carlosdigital16 commented on assets/css/featured-collections.css
> +.featured-collections_hphone p {
Não entendi do que se trata: hphone

2023-08-08 23:24 UTC, carlosdigital16 commented on assets/css/featured-collections.css
> +.content-container-icons {
Usar classe base para todos os seletores

2023-12-07 21:37 UTC, carlosdigital16 commented
O PR ficou desatualizado

2023-12-07 21:37 UTC, closed without merging