SpecialOffer
DCFS5S/dripstore pull request #20
Opened 2023-11-14 23:34 UTC by pedromarino07

Pedro e Daniel

2023-11-15 20:45 UTC, ronnyjohnti requested changes
É melhor alterar o nome de alguns componentes e arquivos.
Não entendi o motivo de existir dois componentes nessa seção da página e a escolha dos nomes.
Verifiquem os comentários e sugestões em algumas linhas dos arquivos.

2023-11-15 20:45 UTC, ronnyjohnti commented on README.md
> +# React + Vite
Melhor remover esse README ou alterar a descrição para condizer com o projeto.

```suggestion
# Dripstore
```

2023-11-15 20:45 UTC, ronnyjohnti commented on src/App.css
É melhor não adicionar arquivos sem conteúdo.

2023-11-15 20:45 UTC, ronnyjohnti commented on src/App.jsx
> +        <div>
Não há necessidade dessa ```div``` encapsulando o componente da página.
```suggestion
```

2023-11-15 20:45 UTC, ronnyjohnti commented on src/App.jsx
> +        </div>
```suggestion
```

2023-11-15 20:45 UTC, ronnyjohnti commented on src/Pages/HomePage/HomePage.css
É melhor não adicionar arquivos sem conteúdo.

2023-11-15 20:45 UTC, ronnyjohnti commented on src/components/ProductList/ProductList.css
É melhor não adicionar arquivos sem conteúdo.

2023-11-15 20:45 UTC, ronnyjohnti commented on src/components/ProductCard/ProductCard.jsx
É mais indicado alterar o nome desse componente, pois não descreve o que o componente é.
Os nomes das classes também estão muito genéricos.

2023-12-05 22:06 UTC, fmatheusteixeira commented on src/Pages/HomePage/HomePage.jsx
> +        <div>
Creio que não precisaria colocar essa <div> envelopando o componente <ProductList />

2023-12-05 22:09 UTC, fmatheusteixeira commented on src/Pages/HomePage/HomePage.jsx
> +        <div>
Creio que não há necessidade de por a  `<div>` envelopando o componente `<ProductList />`

2023-12-05 22:11 UTC, fmatheusteixeira commented on src/components/ProductCard/ProductCard.jsx
> +                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br />Consequatur, aperiam repellat. Soluta maiores culpa expedita <br /> nostrum facilis tempora rem perspiciatis perfere
Sugiro corrigir a endentação em algumas linhas do código.

2023-12-05 22:21 UTC, HannielBarros commented on src/components/ProductCard/ProductCard.jsx
> +export const ProductCard = () => {
Escolher o tipo de como escrever a função arrow function ou do modo comum.

2023-12-05 22:36 UTC, dhitzschkyy commented on README.md
> +# React + Vite
README removido.

2023-12-05 22:38 UTC, dhitzschkyy commented on src/components/ProductCard/ProductCard.jsx
> O componente foi alterado para OfferCard
>  As classes também tiveram seus nomes alterados

2023-12-05 22:59 UTC, fmatheusteixeira commented on src/components/ProductCard/ProductCard.jsx
> +                <h1>Air Jordan edição de <br />colecionador</h1>
Onde foi usado os `<br>` poderia substituir com o width no css para ficar com uma melhor sintaxe

2023-12-05 23:07 UTC, fmatheusteixeira approved these changes

2023-12-05 23:11 UTC, dhitzschkyy approved these changes

2023-12-05 23:14 UTC, ronnyjohnti approved these changes

2023-12-05 23:15 UTC, fmatheusteixeira approved these changes

2023-12-05 23:15 UTC, HannielBarros approved these changes

2023-12-05 23:16 UTC, merged